language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - rvm install ruby-2.2
  - rvm use ruby-2.2
  - gem install toml docker-api mogilefs-client
script:
  - rake build:ci[verbose]
  - rake test:ci[verbose]
