language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cd common
  - cargo build --verbose
  - cargo test --verbose
  - cd ../client
  - cargo build --verbose
  - cargo test --verbose
  - cd ../server
  - cargo build --verbose
  - cargo test --verbose
