[package]
name = "mogilefsd"
version = "0.1.0"
authors = ["Andrew Watts <ahwatts@gmail.com>"]

[[bin]]
name = "mogilefsd"
doc = false

[dependencies]
argparse = "*"
env_logger = "0.3"
lazy_static = "0.1.*"
libc = "0.1"
log = "0.3"
url = "0.2"

[dependencies.iron]
version = "*"
default-features = false

[dependencies.mio]
version = "0.3"
optional = true

[dependencies.threadpool]
version = "0.1"
optional = true

[dev-dependencies]
matches = "0.1"

[features]
default = [ "evented" ]
evented = [ "mio", "threadpool" ]
