[package]
name = "mogilefsd"
version = "0.1.0-alpha"
authors = ["Andrew Watts <ahwatts@gmail.com>"]
build = "build.rs"

[[bin]]
name = "mogilefsd"
doc = false

[dependencies]
argparse = "~0.2.0"
lazy_static = "~0.1.14"
libc = "~0.1.8"
time = "~0.1.32"
url = "~0.2.36"

[dependencies.env_logger]
version = "~0.3.1"
optional = true

[dependencies.iron]
# version = "*"
git = "https://github.com/ahwatts/iron.git"
branch = "bug/http_10"
default-features = false

[dependencies.log]
version = "~0.3.1"
optional = true

[dependencies.mio]
version = "~0.3.5"
optional = true

[dependencies.threadpool]
version = "~0.1.4"
optional = true

[dev-dependencies]
matches = "~0.1.2"

[features]
default = [ "logging" ]
evented = [ "mio", "threadpool" ]
logging = [ "env_logger", "log" ]
