[package]
name = "mogilefsd"
version = "0.1.0"
authors = ["Andrew Watts <ahwatts@gmail.com>"]

[[bin]]
name = "mogilefsd"
doc = false

[dependencies]
argparse = "0.2.0"
env_logger = "0.3.1"
iron = "0.1.20"
lazy_static = "0.1.11"
libc = "0.1.8"
log = "0.3.1"
url = "0.2.35"

[dependencies.mio]
version = "0.3.7"
optional = true

[dependencies.threadpool]
version = "0.1.4"
optional = true

[dev-dependencies]
regex = "0.1.40"

[features]
default = [ "evented" ]
evented = [ "mio", "threadpool" ]
