[package]
name = "mogilefsd"
version = "0.1.0"
authors = ["Andrew Watts <ahwatts@gmail.com>"]

[[bin]]
name = "mogilefsd"
doc = false

[dependencies]
argparse = "*"
lazy_static = "0.1.*"
libc = "0.1"
time = "0.1"
url = "0.2"

[dependencies.env_logger]
version = "0.3"
optional = true

[dependencies.iron]
# version = "*"
git = "https://github.com/ahwatts/iron.git"
branch = "bug/http_10"
default-features = false

[dependencies.log]
version = "0.3"
optional = true

[dependencies.mio]
version = "0.3"
optional = true

[dependencies.threadpool]
version = "0.1"
optional = true

[dev-dependencies]
matches = "0.1"

[features]
default = [ "logging" ]
evented = [ "mio", "threadpool" ]
logging = [ "env_logger", "log" ]
