[package]
name = "mogilefs_common"
description = "Common bits needed for both the MogileFS client and server libs."
version = "0.1.0"
authors = ["Andrew Watts <ahwatts@gmail.com>"]
homepage = "https://github.com/ahwatts/mogilefsd-rs"

[dependencies]
log = "~0.3.1"
url = "~0.2.36"
